create database skhema and fake data
GSG-G11/CleanStead pull request #15
Opened 2022-04-28 11:37 UTC by MostafaQanoo

create database skhema and fake data

2022-04-28 11:39 UTC, Jehad91 approved these changes

2022-04-28 12:10 UTC, IsraaHamdi approved these changes

2022-04-28 12:14 UTC, MohammadAlHabil approved these changes

2022-04-30 02:20 UTC, Mu7ammadAbed requested changes

2022-04-30 02:20 UTC, Mu7ammadAbed commented on server/database/build.sql
> +CREATE TABLE contact (
It's not consistent to mix between plural and singular tables name

2022-04-30 03:18 UTC, Mu7ammadAbed approved these changes

2022-04-30 03:18 UTC, merged