create description card
GSG-G11/CleanStead pull request #41
Opened 2022-04-30 04:15 UTC by MostafaQanoo

relates #22

2022-05-06 16:55 UTC, MohammadAlHabil approved these changes

2022-05-10 01:12 UTC, Jehad91 approved these changes

2022-05-10 23:58 UTC, Mu7ammadAbed requested changes

2022-05-10 23:58 UTC, Mu7ammadAbed commented on client/src/Components/DescriptionContent/index.jsx
> +  });
```suggestion
```

2022-05-11 00:03 UTC, Mu7ammadAbed approved these changes

2022-05-11 01:51 UTC, IsraaHamdi approved these changes

2022-05-11 01:54 UTC, merged