categories cards container
GSG-G11/CleanStead pull request #44
Opened 2022-05-01 09:45 UTC by IsraaHamdi

RELATES #24 
Close #24
![image](https://user-images.githubusercontent.com/88343586/166140605-acb44da1-4e33-4883-9d79-b88887291efa.png)

2022-05-01 16:15 UTC, Mu7ammadAbed requested changes

2022-05-01 16:15 UTC, Mu7ammadAbed commented on client/src/App/index.jsx
> +  const [loading, setLoaging] = useState(false);
```suggestion
  const [loading, setLoading] = useState(false);
```

2022-05-01 16:15 UTC, Mu7ammadAbed commented on client/src/App/index.jsx
> +    setLoaging(true);
```suggestion
    setLoading(true);
```

2022-05-01 16:15 UTC, Mu7ammadAbed commented on client/src/App/index.jsx
>          setCategories(data.data);
```suggestion
      .then(({ data: { data } }) => {
        setCategories(data);
        setLoaging(false);
```

2022-05-01 18:01 UTC, Mu7ammadAbed commented on client/src/App/index.jsx
>        });
```suggestion
      })
      .catch(() => {
        setLoaging(false);
        message.error('حدث خطأ ما');
      });
```

2022-05-06 01:26 UTC, Mu7ammadAbed commented on client/src/Components/Empty/index.jsx
> +  } />;
Why did you use the `span` ?
```suggestion
  return <Empty description={description} />;
```

2022-05-06 01:26 UTC, Mu7ammadAbed commented on client/src/Components/CategoriesCardsContainer/index.jsx
> +          <Empty description={"لا يوجد بيانات"} />
```suggestion
          <Empty description="لا يوجد بيانات" />
```

2022-05-06 01:26 UTC, Mu7ammadAbed commented on client/src/App/index.jsx
> +        // setLoading(false);
```suggestion
        setLoading(false);
```

2022-05-06 01:45 UTC, Mu7ammadAbed commented on client/src/Components/CategoriesCardsContainer/index.jsx
> +  categories: PropTypes.arrayOf(PropTypes.oneOfType(PropTypes.object))
```suggestion
  categories: PropTypes.arrayOf(PropTypes.shape({}))
```

2022-05-06 01:45 UTC, Mu7ammadAbed commented on client/src/Components/CategoriesCardsContainer/index.jsx
> +  loading: PropTypes.bool,
```suggestion
CategoriesCardsContainer.defaultProps = {
  loading: false,
};

CategoriesCardsContainer.propTypes = {
  loading: PropTypes.bool,
```

2022-05-06 01:45 UTC, Mu7ammadAbed commented on client/src/Components/Empty/index.jsx
> +}
```suggestion
EmptyCard.propTypes = {
  description: PropTypes.string
}

EmptyCard.defaultProps = {
  description: 'لا يوجد بيانات',
};
```

2022-05-06 01:45 UTC, Mu7ammadAbed commented on client/src/Pages/Home/index.jsx
> +  categories: PropTypes.arrayOf(PropTypes.oneOfType(PropTypes.object))
```suggestion
  categories: PropTypes.arrayOf(PropTypes.shape({}))
```

2022-05-06 16:11 UTC, Mu7ammadAbed approved these changes

2022-05-06 16:51 UTC, MohammadAlHabil approved these changes

2022-05-06 16:55 UTC, MostafaQanoo approved these changes

2022-05-06 18:31 UTC, Jehad91 approved these changes

2022-05-06 18:32 UTC, merged