Create file structure
GSG-G11/CleanStead pull request #6
Opened 2022-04-26 17:26 UTC by Jehad91

Relates #5
Close #5

2022-04-26 17:30 UTC, MostafaQanoo approved these changes

2022-04-27 00:05 UTC, MohammadAlHabil approved these changes

2022-04-27 06:41 UTC, IsraaHamdi requested changes
delete React.StrictMode and reportWebVitals from index file in client folder
```
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

2022-04-27 10:01 UTC, IsraaHamdi submitted a review, later dismissed

2022-04-27 12:07 UTC, Mu7ammadAbed requested changes
You need to change the type of files in the `server` to `.ts`

2022-04-27 12:07 UTC, Mu7ammadAbed commented on client/package.json
> +    "@testing-library/user-event": "^13.5.0",
```suggestion
```

2022-04-27 12:07 UTC, Mu7ammadAbed commented on client/package.json
> +    "web-vitals": "^2.1.4"
```suggestion
```

2022-04-27 12:07 UTC, Mu7ammadAbed commented on client/src/index.js
> +import App from './App';
You need to export the `App` in order to import it

2022-04-27 12:18 UTC, MostafaQanoo approved these changes

2022-04-27 12:21 UTC, IsraaHamdi approved these changes

2022-04-27 12:23 UTC, MohammadAlHabil approved these changes

2022-04-27 12:25 UTC, Mu7ammadAbed approved these changes

2022-04-27 12:25 UTC, merged