delete service from database
GSG-G11/CleanStead pull request #71
Opened 2022-05-11 23:49 UTC by Jehad91

Relates #61
![image](https://user-images.githubusercontent.com/74710916/167965413-637cad48-9354-43c1-8671-f8cea8fcc37c.png)

2022-05-13 23:53 UTC, Mu7ammadAbed requested changes
This route must be protected and for the admin only, figure out how to handle it, and there's a problem when you try to delete a row while it's being referred from another table with the foreign key if you want to force it to delete the row and the related rows from other table use `ON CASCADE DELETE`.

2022-05-15 08:33 UTC, Mu7ammadAbed commented on server/validation/paramsIdSchema.ts
> +    id: number().required('Id is requried and must be number'),
```suggestion
    id: number().min(1, 'Id must be a positive number').required('Id is requried and must be a number'),
```

2022-05-15 10:51 UTC, Mu7ammadAbed approved these changes

2022-05-15 10:56 UTC, IsraaHamdi approved these changes

2022-05-15 11:00 UTC, MohammadAlHabil approved these changes

2022-05-15 11:02 UTC, MostafaQanoo approved these changes

2022-05-15 11:02 UTC, merged