post categories
GSG-G11/CleanStead pull request #72
Opened 2022-05-12 00:32 UTC by MostafaQanoo

2022-05-13 23:49 UTC, Mu7ammadAbed reviewed
Add more tests for the edge cases.

2022-05-15 07:34 UTC, Mu7ammadAbed requested changes

2022-05-15 07:34 UTC, Mu7ammadAbed commented on test/index.test.ts
> +    expect(res.body.status).toBe(400);
You already tested the status code in line `224`, try to test the response message

2022-05-15 07:50 UTC, Mu7ammadAbed approved these changes

2022-05-15 08:19 UTC, Mu7ammadAbed approved these changes

2022-05-15 08:25 UTC, Jehad91 approved these changes

2022-05-15 08:26 UTC, MohammadAlHabil approved these changes

2022-05-15 08:28 UTC, IsraaHamdi approved these changes

2022-05-15 08:28 UTC, merged