project setup
GSG-G11/CleanStead pull request #8
Opened 2022-04-27 14:38 UTC by IsraaHamdi

project setup
close #4 
Relates #4

2022-04-27 14:43 UTC, Jehad91 submitted a review, later dismissed

2022-04-27 14:45 UTC, MostafaQanoo submitted a review, later dismissed

2022-04-27 14:50 UTC, MohammadAlHabil submitted a review, later dismissed

2022-04-28 02:47 UTC, Mu7ammadAbed requested changes

2022-04-28 02:47 UTC, Mu7ammadAbed commented on tsconfig.json
> +  }
```suggestion
  },
  "include": ["server/**/*.ts"],
```

2022-04-28 02:47 UTC, Mu7ammadAbed commented on tsconfig.json
> +    "rootDir": "./",
```suggestion
```

2022-04-28 02:47 UTC, Mu7ammadAbed commented on tsconfig.json
> +    // "isolatedModules": false,
```suggestion
    "isolatedModules": false,
```

2022-04-28 02:47 UTC, Mu7ammadAbed commented on server/app.ts
> +app.use(express.urlencoded({ extended: true }));
```suggestion
app.use(express.urlencoded({ extended: false}));
```

2022-04-28 02:47 UTC, Mu7ammadAbed commented on server/app.ts
> +});
We should serve this route at the development only, and you should change the response body template from `msg` to `message`
```suggestion
if (NODE_ENV === 'development') {
  app.get('/', (req:Request, res:Response):void => {
    res.json({ message: 'Hello CleanStead' });
  });
}
```

2022-04-28 02:47 UTC, Mu7ammadAbed commented on server/app.ts
> +app.set('port', process.env.PORT || 5000);
```suggestion
dotenv.config();
const {
  env: { PORT, NODE_ENV },
} = process;

app.set('port', PORT || 5000);
app.disable('x-powered-by');
```

2022-04-28 02:50 UTC, Mu7ammadAbed reviewed
This is a very great job, there are only a few notes I mentioned above, for any explanation you can reach me at any time.

2022-04-28 08:02 UTC, Mu7ammadAbed approved these changes

2022-04-28 08:09 UTC, Jehad91 approved these changes

2022-04-28 08:43 UTC, MostafaQanoo approved these changes

2022-04-28 10:49 UTC, MohammadAlHabil approved these changes

2022-04-28 10:49 UTC, merged